dependencies {
    modImplementation(project(":modules:CTNH-Lib")){ transitive = false }
    implementation(project(":modules:CTPP"))

    modImplementation(ctnh.ae2){
        accessTransformers.configure(it) {
            config = project.file('src/main/resources/META-INF/accesstransformer.cfg')
        }
    }
    modImplementation(ctnh.guideme)

    modImplementation(ctnh.glodium)
    modImplementation(ctnh.eae)

    modImplementation(ctnh.pcc)
    modImplementation(ctnh.omnicells)
    modImplementation(ctnh.merequester)
    modImplementation(ctnh.ae2wt)
    modImplementation(ctnh.ae2ct)
    modImplementation(ctnh.ae2cs)
    
    implementation(ctnh.kotlinforforge)
    modImplementation(ctnh.betterp2p)

    modCompileOnly(variantOf(ctnh.curios) { classifier("api") })

    modImplementation(ctnh.clothconfig)

    
    modLocalRuntime(ctnh.curios)
    modLocalRuntime(ctnh.constructionwand)
    modLocalRuntime(ctnh.buildinggadgets)
    modLocalRuntime(forge.spark)
}
